name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: ansible-version
    attributes:
      label: Ansible Version
      description: What version of Ansible are you using? `ansible --version`
      placeholder: |
        ansible 2.11.3
        config file = /etc/ansible/ansible.cfg...
    validations:
      required: true

  - type: textarea
    id: ansible-config
    attributes:
      label: Ansible Configuration
      description: Post the output of `ansible-config dump --only-changed`

  - type: textarea
    id: components
    attributes:
      label: Effected Components
      description: What Ansible components are causing the bug? (firewall, instance)

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List any custom configurations and the steps to reproduce this error
    validations:
      required: true
