name: AccTest Command

on:
  issue_comment:
    types: [ created ]

jobs:
  acctest-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Generate App Installation Token
        id: generate_token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # pin@v1
        with:
          app_id: ${{ secrets.DX_ACCTEST_APP_ID }}
          private_key: ${{ secrets.DX_ACCTEST_PRIV_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@ace7a198016ae74cd286677c7e7f7e266eb18bc4 # pin@v1
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          token: ${{ env.TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: acctest
          named-args: true
          permission: write
