name: Run Documentation Validation

on: pull_request

jobs:
  run-docs-validation:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: update packages
        run: sudo apt-get update -y

      - name: install packages
        run: sudo apt-get install -y make

      - name: setup python 3
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip install -r requirements-dev.txt -r requirements.txt

      - name: install collection
        run: make install

      - name: copy other files to installed collection
        run: cp -r Makefile template scripts ~/.ansible/collections/ansible_collections/linode/cloud/

        # There is not currently a way to set the working directory for subsequent steps
      - name: make temp directory
        run: mkdir tmp
        working-directory: /home/runner/.ansible/collections/ansible_collections/linode/cloud

      - name: copy over old readme
        run: cp README.md tmp/README.md
        working-directory: /home/runner/.ansible/collections/ansible_collections/linode/cloud

      - name: generate new docs
        run: DOCS_PATH=tmp/docs make gendocs
        working-directory: /home/runner/.ansible/collections/ansible_collections/linode/cloud

      - name: compare docs
        run: diff -r docs tmp/docs
        working-directory: /home/runner/.ansible/collections/ansible_collections/linode/cloud

      - name: compare docs
        run: diff -r README.md tmp/README.md
        working-directory: /home/runner/.ansible/collections/ansible_collections/linode/clou

      - name: clean up
        run: rm -rf tmp
        working-directory: /home/runner/.ansible/collections/ansible_collections/linode/cloud
