name: Run Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip3 install -r requirements-dev.txt -r requirements.txt ansible

      - name: run linter
        run: make lint
