# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).

name: release
on:
  workflow_dispatch: null
  release:
    types: [ published ]
jobs:
  galaxyrelease:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .ansible/collections/ansible_collections/linode/cloud
    steps:
      - name: checkout repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3
        with:
          path: .ansible/collections/ansible_collections/linode/cloud

      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: setup python 3
        uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # pin@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip3 install -r requirements-dev.txt -r requirements.txt

      - name: install ansible dependencies
        run: ansible-galaxy collection install amazon.aws:==1.5.1

      - name: publish the collection
        run: make publish
        env:
          GALAXY_TOKEN: ${{ secrets.GALAXY_TOKEN }}
          COLLECTION_VERSION: ${{ github.event.release.tag_name }}
