# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).

name: release
on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: setup python 3
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip3 install -r requirements-dev.txt -r requirements.txt

      - name: install ansible dependencies
        run: ansible-galaxy collection install amazon.aws:==1.5.1

      - name: publish the collection
        run: make publish
        env:
          GALAXY_TOKEN: ${{ secrets.GALAXY_TOKEN }}
          COLLECTION_VERSION: ${{ github.event.release.tag_name }}
